# Generated by Django 2.2.5 on 2020-09-16 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='offerings',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.Offerings'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='payments',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.Payments'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='planning',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.Planning'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='service_options',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='restaurants.ServiceOptions'),
        ),
        migrations.AddField(
            model_name='photo',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='restaurants.Restaurant'),
        ),
    ]
