# Generated by Django 2.2.5 on 2020-09-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_superhost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='currency',
        ),
    ]
