# Generated by Django 2.2.5 on 2020-08-20 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='offerings',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.Offerings'),
        ),
        migrations.AddField(
            model_name='room',
            name='payments',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.Payments'),
        ),
        migrations.AddField(
            model_name='room',
            name='planning',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.Planning'),
        ),
        migrations.AddField(
            model_name='room',
            name='service_options',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='rooms.ServiceOptions'),
        ),
        migrations.AddField(
            model_name='photo',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rooms.Room'),
        ),
    ]
