# Generated by Django 2.2.5 on 2020-08-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20200820_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='numOfGuests',
            field=models.IntegerField(default=1),
        ),
    ]
