# Generated by Django 2.2.5 on 2020-08-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20200814_0118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookedday',
            options={'verbose_name': 'Booked Day'},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='check_out',
        ),
    ]
