# Generated by Django 2.2.5 on 2020-08-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20200819_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookedday',
            options={},
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='check_in',
            new_name='date',
        ),
        migrations.AddField(
            model_name='bookedday',
            name='time',
            field=models.CharField(default='00:00', max_length=6),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.CharField(default='00:00', max_length=6),
        ),
    ]
