# Generated by Django 2.2.5 on 2020-08-20 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20200820_0502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedday',
            old_name='day',
            new_name='date',
        ),
    ]
