# Generated by Django 2.2.5 on 2020-09-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='restaurants',
            field=models.ManyToManyField(blank=True, related_name='lists', to='restaurants.Restaurant'),
        ),
    ]
